[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_FLAGS = "--prefix=/opt/buildhome/cache/node_modules"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "strict-origin-when-cross-origin"