[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20.11.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200